### ISSUE TITLE
USB Installation from network drive hangs

### ISSUE THREAD

**Issue by treyturner** [XorTroll/Goldleaf#176]
I'm using goldtree on a Windows 10 system attempting to push an .nsp stored on a samba/CIFS share on my NAS. When I select the file via the file browser, the Switch and Goldtree appear to hang after accepting the transfer on my Switch.

I copied the .nsp to a local drive and was able to install without issue. It'd be more convenient to support .nsp files on UNC paths so I don't have to copy every .nsp to a local drive for installation.

Thanks for your work!

**Comment by kubik369** [comment]
This isn't a problem with Goldtree/Goldleaf and network drives, this is a problem that it simply gets stuck due to bugs. Installing NSPs from the network drive works because GoldTree doesn't even know that the .nsp is on a samba share, Windows takes care of that transparently. Just try to close both Goldleaf and Goldtree if it hangs, disconnect and reconnect the USB cable and try again.
From my personal experience, after it hangs a few times and then succeeds, I recommend to check the game files in Switch settings - Data management - "your game" - Check files.
I propose closing this issue.

**Comment by lookye** [comment]
I tested this with the 0.5 release and its working fine (as much got fixed and is quite stable now).
Test it yourself and mind closing this?
@treyturner
