### ISSUE TITLE
USB bugs

### ISSUE THREAD

**Issue by XorTroll** [XorTroll/Goldleaf#220]
Since the very first version of Goldleaf USB has been quite unstable.
It's still uncertain if the bugs are caused mainly by Goldleaf or libnx's USB implementation.

**Comment by XorTroll** [comment]
v0.5 refactored USB and it's really stable now, so many of these bugs might be fixed.

**Comment by JaccoVeldscholten** [comment]
0.5 Error:

0x234A02 - Invalid NCA magic

**Comment by patrikhejnar** [comment]
Hi :) 

Just upgraded to 0.5 
Lower transfer speed is back for me, now it s around 20,5mbytes compared to usual 40-45mbytes(version 0.3). 
In 0.4 version the speed lowered even further to around 16.5mbytes.

Thanks for working on this great app.

**Comment by 5H00T4** [comment]
> Hi :)
> 
> Just upgraded to 0.5
> Lower transfer speed is back for me, now it s around 20,5mbytes compared to usual 40-45mbytes(version 0.3).
> In 0.4 version the speed lowered even further to around 16.5mbytes.
> 
> Thanks for working on this great app.

Can confirm, v0.3 installs with around 40MB/s, while 0.5 is only at around 20MB/s.
Tested with same conditions on same Switch, PC, cable etc with both NROs and Goldtrees to confirm it.
The new version is only half as fast!

**Comment by jja2000** [comment]
Goldtree still can't detect my switch it seems, I have the libusbK driver installed with goldleaf opened. Goldleaf detects a usb connection, but goldtree still can't find it. The device shows up in device manager on windows.

I'm running Windows 10 on the host and FW3.0.0 with ams 0.8.7 on the switch

EDIT: I copy pasted it from the original issue I posted this in, this seems more fitting. If I check whatever usb id the switch uses when connected it's always 057e:2000 instead of 3000, I might have accidentally installed the wrong driver although this also happens on Linux. I see in https://github.com/XorTroll/Goldleaf/blob/68e638e2f8faf83bd393ae33ee9ff08afc34e3ae/Goldtree/Goldtree/Program.cs#L109 that it tries to look for 057e:3000 which of course doesn't work if my switch uses the 2000 id.

**Comment by jja2000** [comment]
Hex editing the file (couldn't get the program compiled from source to find the switch) to search for 057e:2000 instead of 057e:3000 works. Seems like you need to check for both.

**Comment by Kaallis** [comment]
Can confirm 0.5 install speed is around 18 mb/s

**Comment by XorTroll** [comment]
I guess this can be closed since currently USB is stable as soon as connection (cable) is fine.

Testing reports that, few errors (most of them not related to actual USB bugs) and I can myself confirm USB works way better than before.
