### ISSUE TITLE
Some nsp's won't install

### ISSUE THREAD

**Issue by jaybepr** [XorTroll/Goldleaf#243]
Hi, I am using Goldleaf 0.4 on FW 7.0.1 to install my nsp's over USB.  Some install with no problem but some others won't.  It will go all the way to the end and it just stop, no error at all just stop and a message on the PC ( content was sent to Goldleaf) .  I restart the Switch and I get a corrupted icon on the Main Screen.  Any ideas, is it me or something needs to be update or change.

**Comment by chou915388** [comment]
You can use Goldleaf 0.2 with Goldtree 0.2 over USB, its works for me to install all nsp and update.
If you have problem while install Goldleaf 0.2, you can choose another place, NAND/SD.

**Comment by nection** [comment]
> Hi, I am using Goldleaf 0.4 on FW 7.0.1 to install my nsp's over USB. Some install with no problem but some others won't. It will go all the way to the end and it just stop, no error at all just stop and a message on the PC ( content was sent to Goldleaf) . I restart the Switch and I get a corrupted icon on the Main Screen. Any ideas, is it me or something needs to be update or change.

The same thing happens to me as you, there is no way with any version of Goldleaf. I hope the new version 0.5 fixes it. Although I do not know if it is a problem detected by the developer.

**Comment by chou915388** [comment]
> > Hi, I am using Goldleaf 0.4 on FW 7.0.1 to install my nsp's over USB. Some install with no problem but some others won't. It will go all the way to the end and it just stop, no error at all just stop and a message on the PC ( content was sent to Goldleaf) . I restart the Switch and I get a corrupted icon on the Main Screen. Any ideas, is it me or something needs to be update or change.
> 
> The same thing happens to me as you, there is no way with any version of Goldleaf. I hope the new version 0.5 fixes it. Although I do not know if it is a problem detected by the developer.

Goldleaf 0.2 + Goldtree 0.2 can solve this problem.

**Comment by Umgajonormal** [comment]
I have the same problem, and looking on the internet, this issue seems to be very  rare

**Comment by XorTroll** [comment]
0.5 is way more stable FYI.

**Comment by mikeybee85** [comment]
I was having the same issue. 

Installing to SD Card, Fat32. It would drop from around 27 mb transfer speed to 0 right at the end. THEN, I would press home, and it would be installed as a corrupt title (spinning circle on dark grey box). Go to settings, data mgmt, delete software, and it was listed as "-_-" with a filesize of 0.1 mb.

 The problem then became trying to uninstall the failed software. In order to uninstall, you have to close the running software (Which in this case, I use the "hold R button" method of launching into homebrew, so a "game" is running. As soon as it closed, I would get a system crash.

Downgraded to 0.3 Goldtree but stayed 0.4 Goldleaf. Got "Are you sure its valid NSP" error. Restarted and tried again, and it started this time but froze at the end again. 

Downgraded Goldleaf to 0.3 as well. Installed like a charm. With transfer speeds of 42 mb (almost twice the speed)

**Comment by chou915388** [comment]
> I was having the same issue.
> 
> Installing to SD Card, Fat32. It would drop from around 27 mb transfer speed to 0 right at the end. THEN, I would press home, and it would be installed as a corrupt title (spinning circle on dark grey box). Go to settings, data mgmt, delete software, and it was listed as "-_-" with a filesize of 0.1 mb.
> 
> The problem then became trying to uninstall the failed software. In order to uninstall, you have to close the running software (Which in this case, I use the "hold R button" method of launching into homebrew, so a "game" is running. As soon as it closed, I would get a system crash.
> 
> Downgraded to 0.3 Goldtree but stayed 0.4 Goldleaf. Got "Are you sure its valid NSP" error. Restarted and tried again, and it started this time but froze at the end again.
> 
> Downgraded Goldleaf to 0.3 as well. Installed like a charm. With transfer speeds of 42 mb (almost twice the speed)

Goldleaf 0.2 + Goldtree 0.2 can solve this problem.
If you want to leave goldleaf without crash, you can press button "-" to leave golfleaf, and press button "home" to go back to system, it will not crash.
And SD card should in exFat?
I have installed about 60 nsp by 0.2+0.2 with 256gb exfat sd card.
