### ISSUE TITLE
Bugs in CFW KOMOS v 11.10.1

### ISSUE THREAD

**Issue by DiSnows** [XorTroll/Goldleaf#244]
Goldleaf crashes when choosing a .NSP to install and in PC mode with Goldtree, when finishing the installation and pressing the HOME menu, Golfleaf CRASH the CFW, forcing the user to restart the console.

**Comment by PiotrZadka** [comment]
Can confirm but I think this is already known issue.

**Comment by chou915388** [comment]
> Goldleaf crashes when choosing a .NSP to install and in PC mode with Goldtree, when finishing the installation and pressing the HOME menu, Golfleaf CRASH the CFW, forcing the user to restart the console.

You can press "-" to leave goldleaf first, and press home. It will not crash.

**Comment by ccidcce32167** [comment]
And when I install Goldleaf(nsp) via Goldleaf(nro) ,it CRASH EVERY TIME. Version 0.4 on KOMOS v 11.10.2

**Comment by PiotrZadka** [comment]
> 
> 
> And when I install Goldleaf(nsp) via Goldleaf(nro) ,it CRASH EVERY TIME. Version 0.4 on KOMOS v 11.10.2

As above use 0.3 for now

**Comment by leandre84** [comment]
> Just try Goldleaf v0.3 for now untill proper v0.5 is released
Or try a pre release build from [https://bsnx.lavatech.top/goldleaf/](https://bsnx.lavatech.top/goldleaf/). Works great here, USB loading via Goldtree 0.4 appears to be broken though.

**Comment by crazy1111** [comment]
I'm using latest Goldleaf pre build from bsnx and I get Error "invalid NCA magic (missing sigpatches?) firmware too low? 4517. I'm on latest atmosphere/kosmos 7.0.1. I'm also new to github and have done extensive searching on Google but need help on how to use Goldtree 0.5 from master build in order to install NSPs?

**Comment by crazy1111** [comment]
I'm using latest Goldleaf pre build from bsnx along with Goldtree 0.3 and I get Error "invalid NCA magic (missing sigpatches?) firmware too low? 4517. I'm on latest atmosphere/kosmos 7.0.1. I'm also new to github and have done extensive searching on Google but need help on how to use Goldtree 0.5 from master build in order to install NSPs?

**Comment by DiSnows** [comment]
Thanks chou915388. Now the biggest problem is installing the NSP. every time of error

**Comment by chou915388** [comment]
> 
> 
> Thanks chou915388. Now the biggest problem is installing the NSP. every time of error

My system is 7.0.1 + Kosmos 11.10.2, and I already used 0.2 goldtree + 0.2 goldleaf via USB to install about 50 nsps.

**Comment by DiSnows** [comment]
chou915388, Is it only working on version 0.2 via USB?

**Comment by XorTroll** [comment]
So... any specific errors you get?

**Comment by DiSnows** [comment]
XorTroll, some nsps, despite being downloaded from the same site and reliable, do not install saying that they made a mistake in the NCA. Another problem is that sometimes it hangs at the moment of connecting to GoldTree, forcing the user to press the HOME button on the switch and restart the CFW. By the way, there are very few NSPs that I was able to install by the program, not by GoldTree.

Well, those are the problems that I am facing and I hope I have helped in the feedback. See that the staff is very dissatisfied with these BUGS in 7.0.1 of Atmosphere, because Tinfoil does not work (or basically died from time to time rsrs)

**Comment by DiSnows** [comment]
Adding that this is happening on all versions.
I'm turning 0.2, but even so, it irritates these errors a lot

**Comment by chou915388** [comment]
> 
> 
> chou915388, Is it only working on version 0.2 via USB?

I can't use 0.3 and 0.4.

**Comment by rfortunatti** [comment]
Can confirm this issue, Kosmos 11.11 (0.8.5/7.0.1) in a clean SD install and all tickets removed. USB installation always led to a hang and Atmosphere crash after pressing the Home button. This happens with Goldleaf 0.4 and 0.5, also the original Tinfoil.

OTH, Goldleaf/Goldtree v0.2 can install NSPs via USB, but the CFW crash also persists. This isn't a direct problem, since Atmosphere can chainload the payload anyway, it is just annoying.

**Comment by mikgit013** [comment]
Hi guys i would like to ask for assistance regarding my goldleaf 0.3

i succesfully downgraded my switch from 9.1.0 to 9.0.1 for the reason that my gold leaf will work again

Issue: the cursor wont move even i press the down button :(

and the method on re installation of goldleaf is to overwrite the goldleaf.nro under the switch folder correct?
