### ISSUE TITLE
cannot install NSPs v0.5

### ISSUE THREAD

**Issue by brnnnrsmssn** [XorTroll/Goldleaf#283]
cannot install NSPs

when i try to install NSPs goldleaf immediately errors.

error
an error ocurred attempting to install the NSP:
error: 0x236e02
module: fs (2)
description: invalid PFS0 (NSP) (4535)

- **Console firmware**: 3.0.0

- **CFW with version**: kosmos 11.11.1 (atmosphere 0.8.5)

- **Goldleaf version**: 0.5

- **Goldtree version**: na

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

i know that these NSPs are valid and work because i used them to install the games on fw7.0.1.
i updated from fw3.0.0 to fw7.0.1 using choidujour, dumped keys using lockpick_rcm, converted XCI to NSP using 4nxci, installed NSP and tested (they launched and played with no issue), downgraded back to fw3.0.0.
at this point the installed games were treated as corrupted and no longer playable. they were deleted and subsequent attempts to install have failed.

i wanted to return to fw3.0.0 to be able to use the cart slot.

**Comment by lookye** [comment]
>downgraded back to fw3.0.0.
at this point the installed games were treated as corrupted and no longer playable.

So can it be, that the game is not made for FW3.0.0? So that this is the reason why it´s not starting?
Also: If the NSP you want to install expects a higher FW (fw ignore can not completely ignore the minimum fw the game expects), it will throw an error.

Please check if the game needs a fw higher than yours (3.0.0). If yes, it´s not Goldleaf but your fw.

**Comment by cem-gurel47** [comment]
Same problem
