### ISSUE TITLE
Simplify multi-NSP installation process

### ISSUE THREAD

**Issue by reshiram1** [XorTroll/Goldleaf#337]
# [ Feature name or title ]

install all nsps of micro sd

## Feature description

hello I request the function of the option micro sd select the folder inside are nsps files for example 50 nsps files and I want to install all 50 files at once not go install 1 by 1 is this possible?

[ Please describe your desired feature as detailed as possible here. ]

## Benefits

[ Describe the benefits the feature would have, aka the things it would make possible to do (or not do). ]

## Additional information

[ In case you have any further ideas, mockups or information about the possible feature, place them here. ]

**Comment by lookye** [comment]
Goldleaf 0.6 supports multi nsp install. Select the folder, press Y, click on special options and choose to install multiple nsp.

**Comment by bwilder4531** [comment]
I think what he meant was, instead of goldleaf asking where to install it on every nsp, make it like what the FBI does, such as when you select to install all nsp’s, it will only ask once for the location and it will just use that choice to install all the other nsp’s. Pretty much like you choose install all, then you can leave it and do something else instead of waiting for it to finish and selecting where to install it again.

**Comment by paoloalby** [comment]
It would be a great idea.
Don't askevery time "Where to install" and make an option for "SD Card location as default".
99% of users will install NSP on SD and not on Switch. 
Make the process faster, don't ask every time the location.

**Comment by reshiram1** [comment]
hello if of course would it be possible? I hope your answers thanks a greeting

**Comment by Avrution** [comment]
Yes, having to confirm every install defeats the purpose of having a batch mode.

**Comment by r0nz3y** [comment]
Oh this would be a fantastic option!!

**Comment by XorTroll** [comment]
On 0.7 install confirmation is only done once :)
