### ISSUE TITLE
Files with special chars like ! are not showing in list on Goldleaf 0.7.3

### ISSUE THREAD

**Issue by gut5** [XorTroll/Goldleaf#413]
# files with special chars like ! don't show 

## Your setup

- **Console firmware**: 9.0.0

- **CFW with version**: AMS 0.9.4

- **Goldleaf version**: 0.7.3

- **Goldtree version**: only using goldleaf on the console

## Bug reproduction
Have a file with special chars in it like !

**Comment by rkmax** [comment]
I can confirm this, some days ago I cannot files with the character `'` in the name

**Comment by noirscape** [comment]
Still an issue, with the ` character.

**Comment by XorTroll** [comment]
Does this only happen on console-memory/sd-card? If so, that's not Goldleaf's issue but the console's

**Comment by gut5** [comment]
I don't use this anymore

**Comment by SapphireMH** [comment]
> Does this only happen on console-memory/sd-card? If so, that's not Goldleaf's issue but the console's

Using Goldleaf's file browser to look for a file on the SD card, yes.
Any files with special characters in the name simply do not show up.

From your statement I take it the official storage drivers of the console simply do not have support for these characters in?

I do wonder if and / or how other content explorers have tackled this, since I've only heard this issue mentioned in Goldleaf's context.

> I don't use this anymore

But other users still do, 2 of us here have the same problem, if you no longer want to be involved please disable notifications and let the dev close the issue once it is handled.
