### ISSUE TITLE
Support for new NSZ 

### ISSUE THREAD

**Issue by MrStimmung** [XorTroll/Goldleaf#417]
# Support for new NSZ 

## Feature description

Add the possibility to install .nsz files.

## Benefits

Benefits would be, that you would be able to install them faster and saving bandwith. Also they dont take as much space as normal nsp files.

## Additional information

[ In case you have any further ideas, mockups or information about the possible feature, place them here. ]

**Comment by XorTroll** [comment]
^
NSZ format is a format made entirely with piracy aims, whereas NSP is an official format used for other stuff. Adding this would position Goldleaf as a piracy tool, which is not what I want.

**Comment by XorTroll** [comment]
As a note, this is one of the main reasons I'm not adding many easy-piracy-orienteed functions like XCI support or gdrive.

**Comment by eXhumer** [comment]
You should also drop NSP support and move more towards a file format that the homebrew that isn't NSP if you don't want your tool used for any sort of piracy. I'm surprised you still support NSPs considering your stance on piracy stuff.

**Comment by Spazzlo** [comment]
what is nsz and why do i want it

**Comment by KirovAir** [comment]
@XorTroll Although I respect your piracy standpoint, I for one like the NSP format better than my cartridges for the sake of archiving and not having to carry game cards with me. Dumping, zipping and unzipping my games for (re) installation is quite the hassle. 
Adopting the format would save some precious time in my use case. Dolphin had a similar format (GCZ?) for similar purposes which I really liked as well. The Wii had a similar format (https://wit.wiimm.de/info/iso-images.html#wdf) which never really came off because of the lacking adoption which was a shame really. 
Still, I understand where you are coming from, just something I wanted to add.

**Comment by glencoe2004** [comment]
Just one of the many reasons Tinfoil is better lol
