### ISSUE TITLE
USB installation hanging and corrupting NSPs.

### ISSUE THREAD

**Issue by e922** [XorTroll/Goldleaf#423]
I am trying to install NSP files through GoldLeaf 0.7.3 using both Quark and NS-USBloader.
No matter what USB port or cord I use, or what USB installer I use with GoldLeaf, my Switch will freeze during installation and the only way to make it continue is if I disconnect and reconnect the USB cable. I've tried other ports and cables, as well as several NSPs.

NSPs will eventually install after a long disconnect/reconnect process, but they always encounter an error about corrupted data after launch.

I've successfully installed NSP files using GoldLeaf 0.7.2 in the past and upgraded because it started freezing and I thought it'd fix it, but it didn't.

Setup is as follows
**Firmware: 9.0.0 | AMS 0.9.4
GoldLeaf 0.7.3
NS-USBLoader 0.8
Quark 0.5**

Let me know if you need any more information.

**Comment by DrappierTechnologies** [comment]
Looking back into posts on forums, discord and here it seems to have been an issue for a while but it doesn't seem to be affecting a whole lot of people. I would love to debug this myself since it's happening to me as well. If someone could point me in the direction of a dockerfile with the toolset I'd need or at least some docs on setup that'd be great.

**Comment by LeroyJennnkinnnns** [comment]
Try FAT32 if you're not already using it.
