### ISSUE TITLE
Increase speed of the network installation 

### ISSUE THREAD

**Issue by zexcster** [XorTroll/Goldleaf#45]
At this moment it's so slow, it's just useless...
No matter what WiFi spot is used with ac/n, etc...
It takes minutes just to send a couple of megabytes
The same package of 8GB can be installed within 5 minutes locally

**Comment by facekapow** [comment]
Yeah, I was thinking this myself, but after reading through the code, the problem is that since the NCAs (the content archives within the NSPs) are retrieved as ranges of bytes (and each range request is made for ~2MB), downloads aren't allowed to reach their maximum download speed (because with downloads, speeds increase over time until reaching a peak; however these downloads are so small that they reach their peak much quicker).

I'm going to see if it's possible to implement these downloads as streaming requests (which would be a boon for install speed).

**Comment by hit0wnzzz** [comment]
Maybe use UDP instead of HTTP?
