### ISSUE TITLE
(Enhancement) Implement NCA signature checks For Safety When Installing

### ISSUE THREAD

**Issue by Aliasim800** [XorTroll/Goldleaf#562]
# Implement NCA signature checks for safety when installing

## Feature description

Please describe your desired feature as detailed as possible here. This would be a great feature to add because it gives the user more safety when installing a desired NSP, 

## Benefits

it offers more protection and protects from potential malware. safety when installing.

## Additional information

You navigate to the NSP you want to install,
you press A to install,
Goldleaf asks where to install the NSP,
It shows information about the NSP,
it should then verify the NSP to see if it is safe or not and if the NSP is fine, the installation continues, if the NSP could be dangerous then another prompt comes up asking wether you want to continue installing the potential dangerous NSP or if you want to back out of the installation to keep you safe.

That is how i would imagine how it would work and i would prefer it to possibly work that way.

Hope this enhancement gets accepted and i look forward to seeing this in a future release.

**Comment by Ammako** [comment]
Would be great, but not gonna happen because XorTroll explicitly does not want to include any piracy-specific features.

If you need to verify NSPs before installing, I would suggest checking them with [NX Game Info](https://github.com/garoxas/NX_Game_Info) first (right-click column header and check Signature to make it show up.)

**Comment by Aliasim800** [comment]
K thanks for your input, I'll go ahead and close this now.
